version: "3.8"
services:
  backend:
    image: backend:latest
    networks:
      - murabei
    ports:
      - "5000:5000"
  frontend:
    image: frontend:latest
    networks:
      - murabei
    ports:
      - "3000:3000"

networks:
  murabei:
    driver: bridge